name: mypipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
       
        
      - name: Run second step
        run: |
          echo Hello, kajal!
          sleep 10s
      - name: Run third step
        run: |
          touch sample.txt
          ls -l
          sleep 10s
          
        
